### ISSUE TITLE
Hello, would you please help us update our paper?

### ISSUE THREAD

**Issue by Luffy03** [PengtaoJiang/Awesome-Weakly-Supervised-Semantic-Segmentation-Papers#5]
Hi, many thanks for your kind sharing, would you please help us share our paper about weakly-supervised learning?

Paper: Modeling the Label Distributions for Weakly-Supervised Semantic Segmentation [arxiv 2024]
Authors: Linshan Wu, Zhun Zhong, Jiayi Ma, Yunchao Wei, Hao Chen, Leyuan Fang, Shutao Li
Link: https://arxiv.org/abs/2403.13225
Paper: Sparsely Annotated Semantic Segmentation with Adaptive Gaussian Mixtures [CVPR 2023]
Authors: Linshan Wu, Zhun Zhong, Leyuan Fang, Xingxin He, Qiang Liu, Jiayi Ma, Hao Chen
Link: https://openaccess.thecvf.com/content/CVPR2023/papers/Wu_Sparsely_Annotated_Semantic_Segmentation_With_Adaptive_Gaussian_Mixtures_CVPR_2023_paper.pdf
Code Link: https://github.com/Luffy03/AGMM-SASS

It would help us a lot! Many thanks!

**Comment by PengtaoJiang** [comment]
@Luffy03  I have updated your paper. Thanks for your interest.

**Comment by Luffy03** [comment]
Many thanks for your help!
